### ISSUE TITLE
Accessing S3 bucket dcnlp-west

### ISSUE THREAD

**Issue by humzaiqbal** [mlfoundations/dclm#16]
Hi! I'm trying to pull down some data to reproduce the baselines and I was running a processing script using the commands specified in the README, doing something like 

```
python3 ray_processing/process.py --source_ref_paths exp_data/datasets/raw_sources/CC_WET_april_2019.json --readable_name c4_v4  --output_dir /path/to/output --config_path baselines/baselines_configs/c4.yaml --source_name cc_april_2019
```

and I get this error 

```
Traceback (most recent call last):
  File "/home/ubuntu/DCLM/ray_processing/process.py", line 192, in <module>
    shard_files = list_shard_files(working_dir, args.num_pages)
  File "/home/ubuntu/DCLM/ray_processing/process.py", line 97, in list_shard_files
    shard_files = [
  File "/home/ubuntu/DCLM/ray_processing/process.py", line 97, in <listcomp>
    shard_files = [
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/boto3/resources/collection.py", line 171, in pages
    for page in pages:
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

After doing a simpler repo it seems I don't have access to the bucket
```
In [9]: import boto3
   ...:
   ...: def list_s3_contents(bucket_name, prefix):
   ...:     s3 = boto3.client('s3')
   ...:     response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix)
   ...:     for obj in response.get('Contents', []):
   ...:         print(obj['Key'])
   ...:
   ...: list_s3_contents('dcnlp-west', 'cc_wet_2019_april_urlfix/')
   
 ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

Is there anything in particular I need to do with my AWS account to get access? Thanks!

**Comment by GeorgiosSmyrnis** [comment]
Hi @humzaiqbal !

Indeed, you should not have access to the bucket - to obtain data for running experiments, you can look into the data that we have on HuggingFace for the competition scales e.g. https://huggingface.co/datasets/mlfoundations/dclm-pool-7b-1x for the 7b-1x scale. These documents can then be filtered as normal using our processing pipeline.

**Comment by humzaiqbal** [comment]
Gotcha thanks, yeah I did wind up downloading from HuggingFace, was a bit confused because the scripts by default seemed to point to using the bucket.

**Comment by humzaiqbal** [comment]
@GeorgiosSmyrnis I have another question about running the processing scripts. I have a directory where I downloaded all the jsonl.zst files for the 400m version and I want to run processing pointing to that directory for the raw data. I made a source_ref JSON file that looks like this. Note that I'm storing the files on an NFS (not on S3). Do the files need to be on S3 for me to use the processing script? 
```{
    "uuid": "f12dc026-cc4a-4203-ba9f-9ba08c5945f9",
    "name": "CC_WET_april_2019",
    "creation_date": "2023_10_16-15_37_18",
    "dataset_url": "/path/to/jsonl/directory",
    "manifest_url": null,
    "sources": [],
    "tokenized": false,
    "tokenizer": null,
    "num_tokens": null,
    "size": 29936838588460,
    "dcnlp_commit_hash": null,
    "dcnlp_diff": null,
    "data_key": "jsonl"
}

```

**Comment by GeorgiosSmyrnis** [comment]
Hi @humzaiqbal,

Currently we only officially support s3 input for the processing script (since we used this setup for most of our experiments) - we are planning to release a version that can work on local data as well.
