### ISSUE TITLE
Unable to run `eval/eval_openlm_ckpt.py`

### ISSUE THREAD

**Issue by dwadden** [mlfoundations/dclm#22]
Hi,

Thanks for the the great work! I'm trying to re-run the dclm eval suite on a huggingface model. When I invoke

```
python eval/eval_openlm_ckpt.py \
    --hf-model [path-to-model-checkpoint] \
    --eval-yaml light.yaml \
    --output-file metrics.json
```

I get an error: 

```
Traceback (most recent call last):
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt.py", line 43, in <module>
    from training.file_utils import download_val_data, load_ppl_yaml
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/file_utils.py", line 20, in <module>
    from training.model_reference import ModelReference
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/model_reference.py", line 6, in <module>
    from training.hyperparameters import Hyperparameters
ModuleNotFoundError: No module named 'training.hyperparameters'
```

I can't find a `hyperparameters` file anywhere. How should I fix this?

Dave

**Comment by Mivg** [comment]
Hey @dwadden ,
Thank you for the kind words.
Sorry about that, it does seem that file was missing. It is now added, can you please try again now?

Maor

**Comment by dwadden** [comment]
Thanks, the module import works but now I'm getting another error. 

The issue happens here: https://github.com/mlfoundations/dclm/blob/main/training/hyperparameters.py#L82. The code points to a `training/configs` folder but no such folder exists. Where should this point to?

```
Traceback (most recent call last):
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt.py", line 43, in <module>
    from training.file_utils import download_val_data, load_ppl_yaml
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/file_utils.py", line 20, in <module>
    from training.model_reference import ModelReference
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/model_reference.py", line 6, in <module>
    from training.hyperparameters import Hyperparameters
  File "/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/hyperparameters.py", line 89, in <module>
    for p in os.listdir(s):
FileNotFoundError: [Errno 2] No such file or directory: '/net/nfs.cirrascale/allennlp/davidw/proj/dclm/training/configs'
```

**Comment by achalddave** [comment]
You actually shouldn't need that folder for HF models. Can you try adding 

```
if not os.path.isdir(s):
    continue
```

before this line: https://github.com/mlfoundations/dclm/blob/main/training/hyperparameters.py#L89

and see if it works?

**Comment by dwadden** [comment]
That worked, thanks! 

The only issue now is that the evaluation time is very slow, I kicked a job off a few hours evaluating a 7B model on a single  L40 and it's about half way through hellaswag (see below). How long do you expect evaluation to take, generally?

```
[Eval batch=1005/10042] Eval on hellaswag_zeroshot/0-shot data
[Eval batch=2009/10042] Eval on hellaswag_zeroshot/0-shot data
[Eval batch=3013/10042] Eval on hellaswag_zeroshot/0-shot data
[Eval batch=4017/10042] Eval on hellaswag_zeroshot/0-shot data
[Eval batch=5022/10042] Eval on hellaswag_zeroshot/0-shot data
```

**Comment by dwadden** [comment]
Sure, I'll send a PR later today!

**Comment by dwadden** [comment]
If I do `torchrun --nproc_per_node <num_gpus> eval/eval_openlm_ckpt.py [args]`, will using more GPU's speed things up? I'm just evaling a 1B model so it fits on a single gpu, so I wasn't sure whether adding more GPU's would help.

**Comment by achalddave** [comment]
It will do dataparallel so yes it will speed things up!

**Comment by dwadden** [comment]
Nice, thanks!

Making progress. I was able to get results with the `--eval-yaml light.yaml` config, it took half an hour on 8 gpus which isn't too bad.

But when I tried to run on with `--eval-yaml mmlu_and_lowvar.yaml`, I kicked off a job at night and it seems like it hung (log below). Is there some reason why changing the eval set should cause issues?

```
2024-07-17T06:11:53.611314103Z [2024-07-16 23:11:53,611] torch.distributed.run: [WARNING] 
2024-07-17T06:11:53.611359636Z [2024-07-16 23:11:53,611] torch.distributed.run: [WARNING] *****************************************
2024-07-17T06:11:53.611363234Z [2024-07-16 23:11:53,611] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
2024-07-17T06:11:53.611366708Z [2024-07-16 23:11:53,611] torch.distributed.run: [WARNING] *****************************************
2024-07-17T06:12:07.601844658Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/b8c4cbba-dce4-4cdd-8459-abc90299b5fb
2024-07-17T06:12:07.601880306Z Loading model into the right classes
2024-07-17T06:12:07.616001078Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/e5a972db-64e5-4c9e-8047-470c15bb5cde
2024-07-17T06:12:07.616024646Z Loading model into the right classes
2024-07-17T06:12:07.617109534Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/81de1ac6-cf10-461d-9460-5848874fc57b
2024-07-17T06:12:07.617127423Z Loading model into the right classes
2024-07-17T06:12:07.716251768Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/63381ea9-8057-4d67-b51e-d9dafe291b1f
2024-07-17T06:12:07.716266071Z Loading model into the right classes
2024-07-17T06:12:07.719904361Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/d8e16cac-eadc-469e-b2ab-8bd523bbbd6b
2024-07-17T06:12:07.719925715Z Loading model into the right classes
2024-07-17T06:12:07.721917490Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/b5d78901-b78a-4ae7-9fa8-df59a1d1fabf
2024-07-17T06:12:07.721924873Z Loading model into the right classes
2024-07-17T06:12:07.796655174Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/31d937d8-f308-4a63-9f8f-65fcac6aa670
2024-07-17T06:12:07.796663978Z Loading model into the right classes
2024-07-17T06:12:07.953286616Z Using temporary working directory: /net/nfs.cirrascale/allennlp/davidw/proj/dclm/eval/eval_openlm_ckpt_temp_dirs/a7fe9234-0144-4ad9-a79b-0fc25973369b
2024-07-17T06:12:07.953320153Z Loading model into the right classes
2024-07-17T06:12:26.511926388Z Done downloading data.
2024-07-17T06:12:27.358239601Z 
Generating train split: 0 examples [00:00, ? examples/s]
Generating train split: 14042 examples [00:00, 162491.70 examples/s]
```

**Comment by dwadden** [comment]
PR here: https://github.com/mlfoundations/dclm/pull/25
