### ISSUE TITLE
Training crashes after some steps

### ISSUE THREAD

**Issue by Yu-Shi** [mlfoundations/dclm#62]
Hello authors, I'm using the training script in this repo to pre-train a LLM under the 400m_1x setup on my data. My data are texts stored in JSONL files, and I skip all the preprocessing steps and directly run the tokenization and training process. After tokenization, I got a data configuration file like this:

```json
{
    "uuid": "54639944-5c05-4e40-bf9c-4f9c76c5d645",
    "name": "my_data_name",
    "creation_date": "2024_08_21-01_42_03",
    "dataset_url": "/a/local/path",
    "manifest_url": "/a/local/path/manifest.jsonl",
    "sources": [],
    "tokenized": true,
    "tokenizer": "/home/yus21/pretrained_models/gpt-neox-20b",
    "num_tokens": 10717103943,
    "size": 0,  
    "dcnlp_commit_hash": "c59dd5878c8bd1965b4894e20d8a091e8fdeac7a",
    "dcnlp_diff": "...(omitted)",
    "data_key": "json.gz",
    "sampling_yaml": null
}
```

(I modified some code to make it run on my local machine, since I don't store my data on AWS S3. The size field is not important, right?)

In the output directory, there are 639 tar files, a configuration file, and a manifest file `manifest.json`. The manifest file looks like:

```
{"shard": "00000001", "num_sequences": 8192}
{"shard": "00000002", "num_sequences": 8192}
{"shard": "00000003", "num_sequences": 8192}
...
{"shard": "00000638", "num_sequences": 8192}
{"shard": "00000639", "num_sequences": 3911}
```

Then I run pre-training using a command like this:

```bash
torchrun --nproc-per-node 8 -m training.train -- --scale 411m_1x  --data-config /path/to/previous/config  --logs /path/to/log
``` 

The pre-training works fine at the beginning, but it soon crashes, giving the following error:

```
2024-08-21,11:49:49 | INFO | Train Epoch: 0 [102912/786432 (13%)] Loss: 5.809 Data (t): 0.021 Batch (t): 2.873, 366841./s, 45855.2/s/gpu LR: 0.000302
2024-08-21,11:50:46 | INFO | Train Epoch: 0 [113152/786432 (14%)] Loss: 5.640 Data (t): 0.019 Batch (t): 2.866, 367852./s, 45981.5/s/gpu LR: 0.000332
2024-08-21,11:51:43 | INFO | Train Epoch: 0 [123392/786432 (16%)] Loss: 5.483 Data (t): 0.017 Batch (t): 2.862, 353256./s, 44157.1/s/gpu LR: 0.000362
2024-08-21 11:52:21,088 - __main__ - ERROR - Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/mix.py", line 64, in random_samples
    yield next(sources[i])
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/pipeline.py", line 71, in iterator
    for sample in self.iterator1():
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 490, in _batched
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 253, in _select
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 400, in _to_tuple
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 375, in _map_dict
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 325, in _rename
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 288, in _decode
    for sample in data:
  File "/home/yus21/dclm/.venv/lib/python3.10/site-packages/webdataset/filters.py", line 217, in _shuffle
    for sample in data:
  File "/home/yus21/open_lm/open_lm/data.py", line 166, in group_by_keys_nothrow
    fname, value = filesample["fname"], filesample["data"]
KeyError: 'fname'
```

I have no idea of the cause of the error. Can you share some insights with me on this error? Thanks in advance for your help.

**Comment by GeorgiosSmyrnis** [comment]
Hi @Yu-Shi ,

Could you post the output of `tar -tf` using one of the tarfiles as input? Intuitively it seems to me that the tarfiles are somehow malformed (or at least one of them - if the manifest lists size 8192 for all of them, maybe it's the last one?)

**Comment by Yu-Shi** [comment]
I run the following script in the data directory:

```bash
for file in *.tar; do if ! tar -tf "$file" > /dev/null 2>&1; then echo "Corrupted: $file"; fi; done
```

No corrupted files are found.

Note that the last line of `manifest.json` is: `{"shard": "00000639", "num_sequences": 3911}`, `num_sequences` is not 8192. Is it OK?

**Comment by Yu-Shi** [comment]
The output of `tar -tf` on a tarfile gives a list of `*json.gz` files, like: 

```
baa3d4799b961318b8a1d8761d73a782.json.gz
f892fdc22ece2e4b719d800a3e4ca67d.json.gz
81f0f97642f6993b74d284951b14ef81.json.gz
5c67d9ba5c84bd087a9a4e39fbee3af6.json.gz
0561c057ba00b7ee3422d7a9248c1f12.json.gz
054e613de651eae6cfc107504bc0bd75.json.gz
77563b164e51fcaf13af30117ea0b466.json.gz
61754bdc33d4182123bbc77f95754b1b.json.gz
6357736c6a1e89fab33952a224214a4d.json.gz
75b8bcfb5b03b09e262e8c8523b30661.json.gz
1470aeadd4d379722d681bb13be85269.json.gz
...
```

**Comment by Yu-Shi** [comment]
I deleted all tokenized data and re-ran the tokenization process, then started pre-training, and found that the problem persists, and it always crashes at somewhere between 16%~17% of epoch 0. 

To overcome this problem, I then modified the `group_by_keys_nothrow` function from `open_lm/data.py` as follows:

```python
def group_by_keys_nothrow(data, keys=base_plus_ext, lcase=True, suffixes=None, handler=None):
    """Return function over iterator that groups key, value pairs into samples.

    :param keys: function that splits the key into key and extension (base_plus_ext)
    :param lcase: convert suffixes to lower case (Default value = True)
    """
    current_sample = None
    for filesample in data:
        assert isinstance(filesample, dict)
        try:
            fname, value = filesample["fname"], filesample["data"]
        except KeyError:
            logging.warning(f"Missing key in filesample: {filesample}")
            continue
        prefix, suffix = keys(fname)
        if prefix is None:
            continue
        if lcase:
            suffix = suffix.lower()
        # FIXME webdataset version throws if suffix in current_sample, but we have a potential for
        #  this happening in the current LAION400m dataset if a tar ends with same prefix as the next
        #  begins, rare, but can happen since prefix aren't unique across tar files in that dataset
        if current_sample is None or prefix != current_sample["__key__"] or suffix in current_sample:
            if valid_sample(current_sample):
                yield current_sample
            current_sample = dict(__key__=prefix, __url__=filesample["__url__"])
        if suffixes is None or suffix in suffixes:
            current_sample[suffix] = value
    if valid_sample(current_sample):
        yield current_sample
```

That is, skip the `filesample` if there is a `KeyError`. I have the following observations:

- The training process runs smoothly after I make this change
- The `filesample` that causes a `KeyError` is always an empty dict
- It happens every 16%~17% of data from epoch 0: The error occurs at 16%, 33%, 50%, ...

The printed log looks like this:

```
...
After FSDP parameter num: 51,458,176 on rank 6
After FSDP 0.239 GB on rank 6
2024-08-21,16:48:12 | INFO | ==> Checkpoint 1, steps 1536, tokens seen 1610612736
2024-08-21,16:48:12 | INFO | ==> Checkpoint 2, steps 3072, tokens seen 3221225472
2024-08-21,16:48:12 | INFO | ==> Checkpoint 3, steps 4608, tokens seen 4831838208
2024-08-21,16:48:12 | INFO | ==> Checkpoint 4, steps 6144, tokens seen 6442450944
2024-08-21,16:48:12 | INFO | ==> Checkpoint 5, steps 7680, tokens seen 8053063680
2024-08-21,16:48:12 | INFO | ==> Checkpoint 6, steps 7850, tokens seen 8231321600
2024-08-21,16:48:12 | INFO | Number of checkpoints to be made: 6.Number will be greater in case of unexpected failures leading to the use of more shards
2024-08-21,16:48:12 | WARNING | 5 were requested, but 6 will be made. This behavior is a best effort in checkpointing for the desired amount of epochs, and depends on the number of workers and gpus used, as well as the size of the shards themselves.
2024-08-21,16:48:12 | INFO | Start epoch 0
2024-08-21,16:48:12 | INFO | => epoch 0, training on ['/path/to/data/{00000050,00000631,00000579,00000215,00000605,00000493,00000577,00000350,00000521,00000479,00000482,00000589,00000592,00000051,00000535,00000432,00000052,00000210,00000027,00000031,00000509,00000546,00000237,00000129,00000147,00000445,00000197,00000060,00000280,00000244,00000389,00000429,00000281,00000109,00000123,00000308,00000110,00000155,00000103,00000400,00000207,00000239,00000386,00000288,00000111,00000514,00000119,00000278,00000591,00000283,00000242,00000599,00000150,00000460,00000161,00000025,00000473,00000014,00000248,00000144,00000461,00000368,00000488,00000434,00000120,00000584,00000537,00000335,00000337,00000559,00000307,00000467,00000065,00000567,00000403,00000040,00000538,00000602,00000039,00000637,00000154,00000451,00000016,00000571,00000159,00000177,00000572,00000199,00000287,00000250,00000022,00000153,00000334,00000576,00000426,00000398}.tar']
2024-08-21,16:48:16 | INFO | Train Epoch: 0 [   512/786432 (0%)] Loss: 11.290 Data (t): 0.379 Batch (t): 3.918, 267644./s, 33455.5/s/gpu LR: 0.000002
2024-08-21,16:49:13 | INFO | Train Epoch: 0 [ 10752/786432 (1%)] Loss: 9.847 Data (t): 0.017 Batch (t): 2.845, 369054./s, 46131.8/s/gpu LR: 0.000031
2024-08-21,16:50:10 | INFO | Train Epoch: 0 [ 20992/786432 (3%)] Loss: 8.686 Data (t): 0.018 Batch (t): 2.851, 367116./s, 45889.5/s/gpu LR: 0.000062
2024-08-21,16:51:07 | INFO | Train Epoch: 0 [ 31232/786432 (4%)] Loss: 7.839 Data (t): 0.015 Batch (t): 2.859, 366447./s, 45805.9/s/gpu LR: 0.000092
2024-08-21,16:52:04 | INFO | Train Epoch: 0 [ 41472/786432 (5%)] Loss: 7.360 Data (t): 0.017 Batch (t): 2.861, 367164./s, 45895.5/s/gpu LR: 0.000121
2024-08-21,16:53:01 | INFO | Train Epoch: 0 [ 51712/786432 (7%)] Loss: 6.973 Data (t): 0.016 Batch (t): 2.869, 364962./s, 45620.3/s/gpu LR: 0.000151
2024-08-21,16:53:59 | INFO | Train Epoch: 0 [ 61952/786432 (8%)] Loss: 6.664 Data (t): 0.017 Batch (t): 2.864, 365423./s, 45677.9/s/gpu LR: 0.000181
2024-08-21,16:54:56 | INFO | Train Epoch: 0 [ 72192/786432 (9%)] Loss: 6.388 Data (t): 0.016 Batch (t): 2.860, 366478./s, 45809.7/s/gpu LR: 0.000211
2024-08-21,16:55:53 | INFO | Train Epoch: 0 [ 82432/786432 (10%)] Loss: 6.157 Data (t): 0.017 Batch (t): 2.864, 367441./s, 45930.2/s/gpu LR: 0.000241
2024-08-21,16:56:50 | INFO | Train Epoch: 0 [ 92672/786432 (12%)] Loss: 5.964 Data (t): 0.018 Batch (t): 2.867, 364934./s, 45616.8/s/gpu LR: 0.000272
2024-08-21,16:57:48 | INFO | Train Epoch: 0 [102912/786432 (13%)] Loss: 5.818 Data (t): 0.016 Batch (t): 2.862, 364176./s, 45522.0/s/gpu LR: 0.000302
2024-08-21,16:58:45 | INFO | Train Epoch: 0 [113152/786432 (14%)] Loss: 5.644 Data (t): 0.016 Batch (t): 2.866, 367739./s, 45967.4/s/gpu LR: 0.000332
2024-08-21,16:59:42 | INFO | Train Epoch: 0 [123392/786432 (16%)] Loss: 5.475 Data (t): 0.016 Batch (t): 2.863, 354067./s, 44258.4/s/gpu LR: 0.000362
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:08 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:11 | WARNING | Missing key in filesample: {}
2024-08-21,17:00:40 | INFO | Train Epoch: 0 [133632/786432 (17%)] Loss: 5.317 Data (t): 0.017 Batch (t): 2.865, 366572./s, 45821.5/s/gpu LR: 0.000392
2024-08-21,17:01:37 | INFO | Train Epoch: 0 [143872/786432 (18%)] Loss: 5.200 Data (t): 0.017 Batch (t): 2.876, 367738./s, 45967.2/s/gpu LR: 0.000421
2024-08-21,17:02:34 | INFO | Train Epoch: 0 [154112/786432 (20%)] Loss: 5.018 Data (t): 0.017 Batch (t): 2.867, 366646./s, 45830.8/s/gpu LR: 0.000452
2024-08-21,17:03:32 | INFO | Train Epoch: 0 [164352/786432 (21%)] Loss: 4.887 Data (t): 0.016 Batch (t): 2.868, 365354./s, 45669.3/s/gpu LR: 0.000481
2024-08-21,17:04:31 | INFO | Train Epoch: 0 [174592/786432 (22%)] Loss: 4.703 Data (t): 0.017 Batch (t): 2.939, 334169./s, 41771.1/s/gpu LR: 0.000512
2024-08-21,17:05:30 | INFO | Train Epoch: 0 [184832/786432 (24%)] Loss: 4.524 Data (t): 0.019 Batch (t): 2.991, 365187./s, 45648.3/s/gpu LR: 0.000541
2024-08-21,17:06:28 | INFO | Train Epoch: 0 [195072/786432 (25%)] Loss: 4.375 Data (t): 0.019 Batch (t): 2.862, 364829./s, 45603.7/s/gpu LR: 0.000571
2024-08-21,17:07:25 | INFO | Train Epoch: 0 [205312/786432 (26%)] Loss: 4.212 Data (t): 0.018 Batch (t): 2.876, 365245./s, 45655.7/s/gpu LR: 0.000602
2024-08-21,17:08:23 | INFO | Train Epoch: 0 [215552/786432 (27%)] Loss: 4.127 Data (t): 0.021 Batch (t): 2.873, 365480./s, 45684.9/s/gpu LR: 0.000632
2024-08-21,17:09:20 | INFO | Train Epoch: 0 [225792/786432 (29%)] Loss: 4.029 Data (t): 0.019 Batch (t): 2.876, 365649./s, 45706.1/s/gpu LR: 0.000661
2024-08-21,17:10:18 | INFO | Train Epoch: 0 [236032/786432 (30%)] Loss: 3.927 Data (t): 0.015 Batch (t): 2.878, 364690./s, 45586.2/s/gpu LR: 0.000692
2024-08-21,17:11:15 | INFO | Train Epoch: 0 [246272/786432 (31%)] Loss: 3.840 Data (t): 0.017 Batch (t): 2.866, 366481./s, 45810.1/s/gpu LR: 0.000722
2024-08-21,17:12:13 | INFO | Train Epoch: 0 [256512/786432 (33%)] Loss: 3.777 Data (t): 0.017 Batch (t): 2.877, 366695./s, 45836.9/s/gpu LR: 0.000752
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:27 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:12:30 | WARNING | Missing key in filesample: {}
2024-08-21,17:13:10 | INFO | Train Epoch: 0 [266752/786432 (34%)] Loss: 3.726 Data (t): 0.016 Batch (t): 2.860, 365642./s, 45705.2/s/gpu LR: 0.000781
...
```

I'm still confused about this problem and wonder if my modification will bring unexpected implications.

**Comment by GeorgiosSmyrnis** [comment]
Hi @Yu-Shi ,

Is your `webdataset` version after 0.2.90? After looking into this, this seems to be an issue with a parameter added in a `webdataset` function, namely https://github.com/webdataset/webdataset/blob/7e33c40825c5157a0c5c4def050d4692b491b68f/webdataset/tariterators.py#L156

This doesn't appear to be present in `webdataset<=0.2.90`, so I would recommend downgrading for now while this dependency is fixed in `open_lm` (in my own tested environment I have `webdataset==0.2.86`, so you can try that as well).

**Comment by GeorgiosSmyrnis** [comment]
Also to answer your follow up questions:
- I would recommend not changing the training code unless you check in with us.
- The last shard being smaller most likely means that you ran out of data, so it's normal.

I hope the above help!

**Comment by Yu-Shi** [comment]
@GeorgiosSmyrnis Thank you for your help! Downgrading `webdataset` to 0.2.86 solves this issue.

**Comment by GeorgiosSmyrnis** [comment]
Hi @Yu-Shi ,

Glad to hear that this is resolved!
