### ISSUE TITLE
Cannot train

### ISSUE THREAD

**Issue by camilobrownpinilla** [mlfoundations/dclm#97]
Hello!

I am trying to do a training run by running the following command
`torchrun --nproc-per-node 4 -m DCLM.training.train -- --scale 411m_1x --data-config /path/to/config.json --logs ./DCLM/logs --torchcompile`

However, I get the following error:
`[W1120 16:44:30.864937119 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
2024-11-20 16:44:35,873 - __main__ - INFO - Running training on scale: 411m_1x
2024-11-20 16:44:35,873 - __main__ - INFO - World size is 4.
Running with args:
['--workers', '2', '--precision', 'amp_bfloat16', '--global-batch-size', '512', '--log-every-n-steps', '20', '--grad-clip-norm', '1', '--lr', '0.003', '--warmup', '2000', '--model', 'training/open_lm_configs/d=1024_l=24_h=8.json', '--wd', '0.033', '--beta2', '0.95', '--epochs', '5', '--resume', 'latest', '--seed', '124', '--accum-freq', '8', '--model-norm', 'gain_only_lp_layer_norm', '--delete-previous-checkpoint', '--lr-cooldown-end', '3e-05', '--logs', './DCLM/logs', '--attn-name', 'auto', '--log-logit-mean', '--data-tolerate-error-p', '0.09', '--data-tolerate-num-ckpts', '0', '--train-num-samples', '1646465024', '--dataset-manifest', '/path/to/manifest.jsonl', '--data-key', 'json.gz', '--name', 'pipeline_test-d=1024_l=24_h=8-warm=2000-lr=0p003-wd=0p033-cd=3e-05-bs=512-mult=1-seed=124-tokens=8232325120', '--fsdp', '--fsdp-amp', '--fsdp-limit-all-gathers', '--qk-norm', '--z-loss', '0.0001', '--torchcompile']Running with args:
['--workers', '2', '--precision', 'amp_bfloat16', '--global-batch-size', '512', '--log-every-n-steps', '20', '--grad-clip-norm', '1', '--lr', '0.003', '--warmup', '2000', '--model', 'training/open_lm_configs/d=1024_l=24_h=8.json', '--wd', '0.033', '--beta2', '0.95', '--epochs', '5', '--resume', 'latest', '--seed', '124', '--accum-freq', '8', '--model-norm', 'gain_only_lp_layer_norm', '--delete-previous-checkpoint', '--lr-cooldown-end', '3e-05', '--logs', './DCLM/logs', '--attn-name', 'auto', '--log-logit-mean', '--data-tolerate-error-p', '0.09', '--data-tolerate-num-ckpts', '0', '--train-num-samples', '1646465024', '--dataset-manifest', '/path/to/manifest.jsonl', '--data-key', 'json.gz', '--name', 'pipeline_test-d=1024_l=24_h=8-warm=2000-lr=0p003-wd=0p033-cd=3e-05-bs=512-mult=1-seed=124-tokens=8232325120', '--fsdp', '--fsdp-amp', '--fsdp-limit-all-gathers', '--qk-norm', '--z-loss', '0.0001', '--torchcompile']
Running with args:
['--workers', '2', '--precision', 'amp_bfloat16', '--global-batch-size', '512', '--log-every-n-steps', '20', '--grad-clip-norm', '1', '--lr', '0.003', '--warmup', '2000', '--model', 'training/open_lm_configs/d=1024_l=24_h=8.json', '--wd', '0.033', '--beta2', '0.95', '--epochs', '5', '--resume', 'latest', '--seed', '124', '--accum-freq', '8', '--model-norm', 'gain_only_lp_layer_norm', '--delete-previous-checkpoint', '--lr-cooldown-end', '3e-05', '--logs', './DCLM/logs', '--attn-name', 'auto', '--log-logit-mean', '--data-tolerate-error-p', '0.09', '--data-tolerate-num-ckpts', '0', '--train-num-samples', '1646465024', '--dataset-manifest', '/path/to/manifest.jsonl', '--data-key', 'json.gz', '--name', 'pipeline_test-d=1024_l=24_h=8-warm=2000-lr=0p003-wd=0p033-cd=3e-05-bs=512-mult=1-seed=124-tokens=8232325120', '--fsdp', '--fsdp-amp', '--fsdp-limit-all-gathers', '--qk-norm', '--z-loss', '0.0001', '--torchcompile']

Running with args:
['--workers', '2', '--precision', 'amp_bfloat16', '--global-batch-size', '512', '--log-every-n-steps', '20', '--grad-clip-norm', '1', '--lr', '0.003', '--warmup', '2000', '--model', 'training/open_lm_configs/d=1024_l=24_h=8.json', '--wd', '0.033', '--beta2', '0.95', '--epochs', '5', '--resume', 'latest', '--seed', '124', '--accum-freq', '8', '--model-norm', 'gain_only_lp_layer_norm', '--delete-previous-checkpoint', '--lr-cooldown-end', '3e-05', '--logs', './DCLM/logs', '--attn-name', 'auto', '--log-logit-mean', '--data-tolerate-error-p', '0.09', '--data-tolerate-num-ckpts', '0', '--train-num-samples', '1646465024', '--dataset-manifest', '/path/to/manifest.jsonl', '--data-key', 'json.gz', '--name', 'pipeline_test-d=1024_l=24_h=8-warm=2000-lr=0p003-wd=0p033-cd=3e-05-bs=512-mult=1-seed=124-tokens=8232325120', '--fsdp', '--fsdp-amp', '--fsdp-limit-all-gathers', '--qk-norm', '--z-loss', '0.0001', '--torchcompile']
[W1120 16:45:06.293936192 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1120 16:45:06.293936396 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1120 16:45:06.293936451 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1120 16:45:06.293961613 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
2024-11-20,16:45:06 | INFO | No latest resume checkpoint found in ./DCLM/logs/pipeline_test-d=1024_l=24_h=8-warm=2000-lr=0p003-wd=0p033-cd=3e-05-bs=512-mult=1-seed=124-tokens=8232325120/checkpoints.
2024-11-20,16:45:10 | INFO | Running in distributed mode with multiple processes. Device: cuda:0.Process (global: 0, local 0), total 4.
2024-11-20 16:45:10,327 - __main__ - ERROR - Pass a pre-defined open_lm model name or a json config
2024-11-20,16:45:10 | ERROR | Pass a pre-defined open_lm model name or a json config
2024-11-20 16:45:10,338 - __main__ - ERROR - Traceback (most recent call last):
  File "/n/home11/cbrownpinilla/color_filter/DCLM/training/train.py", line 105, in <module>
    main(open_lm_args)
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/main.py", line 475, in main
    model = create_model(args)
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/model.py", line 503, in create_model
    model = Transformer(create_params(args))
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/model.py", line 434, in create_params
    raise ValueError("Pass a pre-defined open_lm model name or a json config")
ValueError: Pass a pre-defined open_lm model name or a json config

2024-11-20,16:45:10 | ERROR | Traceback (most recent call last):
  File "/n/home11/cbrownpinilla/color_filter/DCLM/training/train.py", line 105, in <module>
    main(open_lm_args)
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/main.py", line 475, in main
    model = create_model(args)
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/model.py", line 503, in create_model
    model = Transformer(create_params(args))
  File "/n/home11/cbrownpinilla/.local/lib/python3.10/site-packages/open_lm/model.py", line 434, in create_params
    raise ValueError("Pass a pre-defined open_lm model name or a json config")
ValueError: Pass a pre-defined open_lm model name or a json config`

I created my data config, and it looks like this:

`{"uuid": "00bd2d37-5a20-4c04-b586-578e3a5ea668", "name": "pipeline_test", "dataset_url": "/local/path/", "manifest_url": "/local/path/manifest.jsonl", "sources": [], "tokenized": true, "num_tokens": 20490, "size": 30760, "dcnlp_commit_hash": "aaa3362aeb60eed8e7166b03f1ac1e6205d23d2e", "dcnlp_diff": "(omitted)", "sampling_yaml": null}`

I've tried launching training with dataset configs that were included stock and still get the same behavior.

Any help would be greatly appreciated. Thank you!

**Comment by camilobrownpinilla** [comment]
Fixed. It seems it was a path issue as the model path expects that you run training from within the DCLM directory.
